mgmt_ipv4: 172.20.20.5
mgmt_ipv6: 3fff:172:20:20::5
router_id: 100.64.0.4
router_id_v6: 2001::100:64:0:4
vtep: 100.65.0.4
vtep_v6: 2002::100:65:0:4
bgp_as: 4200000004
ip_virtual_router_mac_address: 0a:00:ca:fe:00:01
switch_group: "0001"
ethernet_interfaces:
- name: Ethernet1
  shutdown: false
  peer: spine1
  peer_interface: Ethernet2
  peer_type: spine
- name: Ethernet2
  shutdown: false
  peer: spine2
  peer_interface: Ethernet2
  peer_type: spine
- name: Ethernet3
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: host1
  peer_interface: Ethernet2
  peer_type: esi
  port_profile: compute_servers_dc1
- name: Ethernet4
  shutdown: true
  channel_group:
    id: 2
    mode: active
  peer: host3
  peer_interface: Ethernet2
  peer_type: esi
  port_profile: compute_servers_dc1
- name: Ethernet5
  shutdown: false
  ipv4_address: 191.0.0.3/31
  peer: isp-router2
  peer_interface: Ethernet1
  peer_type: external
  port_profile: isp-dc1-secondary