stages:
  - build
  - approve
  - deploy
  
fabric_build:
  stage: build
  tags:
    - build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /CONFIG BUILD BY CICD/'
      when: never
    - when: always
  before_script:
    - git config --global alias.hist "log --all --decorate --oneline --graph"
    - git config --global user.name "bnet-containerlab-runner"
    - git config --global user.email "lab@danielblazek.cz"
  script:
    - git fetch origin $CI_COMMIT_REF_NAME
    - git checkout -B $CI_COMMIT_REF_NAME origin/$CI_COMMIT_REF_NAME
    - ansible-playbook eos-eapi/play_fabric_config.yml --tags build -i eos-eapi/inventory.yml
    - git add eos-eapi/configs/.
    - git commit -am "$(git log -1 --pretty=%s) [CONFIG BUILD BY CICD]" || echo "Nothing to commit"
    - git push https://oauth2:${GITLAB_TOKEN}@gitlab.com/DanielBlazek18/networkinglabs.git HEAD:$CI_COMMIT_REF_NAME

approve_deploy:
  stage: approve
  script:
    - echo "Approval granted. Proceeding..."
  when: manual
  allow_failure: false
  only:
    - main

fabric_deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - ansible-playbook eos-eapi/play_fabric_config.yml --tags deploy -i eos-eapi/inventory.yml
  only:
    - main