---
- name: "Test tenant config"
  hosts: leaf
  gather_facts: no
  tasks:
    - name: Test tenant config task
      arista.eos.eos_config:
        lines:
          - vlan 200
          - rd 10.0.0.1:200
          - route-target both 200:200
        parents: "router bgp {{ bgp_as }}"
        replace: block