vlans:
  - id: 10
    name: L2_VLAN_10
  - id: 20
    name: L2_VLAN_20
  - id: 3000
    name: L2_VLAN_3000
vrfs:
  - name: vrf-01
    vni: 1010
    svis:
      - id: 10
        name: vrf-01_vlan10
        enabled: true
        ipv4_address: 10.0.10.1/24
  - name: vrf-02
    vni: 1020
    svis:
      - id: 20
        name: vrf-02_vlan20
        enabled: true
        ipv4_address: 10.0.20.1/24
