---
- name: "System configuration"
  template:
    src: "{{ansible_network_os}}/system.j2"
    dest: "{{build_dir}}/00_system.cfg"
  tags: system

- name: "Interface configuration"
  template:
    src: "{{ansible_network_os}}/intf.j2"
    dest: "{{build_dir}}/01_intf.cfg"
  tags: intf

- name: "Fabric configuration"
  template:
    src: "{{ansible_network_os}}/fabric.j2"
    dest: "{{build_dir}}/02_fabric.cfg"
  tags: fabric